// For moving p2p but using moption profile generated by Ruckig

#include <Arduino.h>
#include "FastAccelStepper.h"
#include "TMCStepper.h"
#include "motor_init.h"
#include <math.h>
#include <ArduinoEigen.h>
#include <ruckig/ruckig.hpp>

using namespace ruckig;
const int DOFs = 2;

// 1. Initialize Ruckig with a 1ms control cycle (0.001 seconds)
// The '8' is the maximum number of waypoints you plan to send at once
Ruckig<DOFs> ruck(0.01);
InputParameter<DOFs> input;
OutputParameter<DOFs> output;


const float L1 = 110.4;
const float L2 = 142.0;
const int TRAJECTORY_STEPS = 200; // 30 points for 30mm (1mm resolution)

struct Waypoint {
  float j1_angle;
  float j2_angle;
};
Waypoint path[TRAJECTORY_STEPS];


// ================= UART PINS =================
#define TMC2_RX 16
#define TMC2_TX 17

void setupRuckig() {
    // 1. ALL MATH IS NOW IN "REVOLUTIONS" INSTEAD OF DEGREES
    // 650 deg/s / 360 = 1.8 rev/s
    input.max_velocity = {1.8, 1.8};       
    
    // 3000 deg/s^2 / 360 = 8.3 rev/s^2
    input.max_acceleration = {2.3, 2.3}; 
    
    // 30000 deg/s^3 / 360 = 83.3 rev/s^3
    input.max_jerk = {20.3,23.3};         

    input.current_position = {0.0, 0.0};
    input.current_velocity = {0.0, 0.0};
    input.current_acceleration = {0.0, 0.0};

    // 3600 degrees / 360 = 10 Revolutions!
    input.target_position = {0.0, 0.0};
    input.target_velocity = {0.0, 0.0}; 
    input.target_acceleration = {0.0, 0.0};
    
    input.synchronization = Synchronization::Time;

    // Validation Check...
    try {
        ruck.validate_input(input);
        Serial.println("Ruckig Input Validation: SUCCESS");
    } catch (const std::exception& e) {
        Serial.print("FATAL RUCKIG ERROR: ");
        Serial.println(e.what());
        while (true) delay(1000);
    }
}


void setup()
{   
    Serial.begin(115200);
    Serial2.begin(115200, SERIAL_8N1, TMC2_RX, TMC2_TX);

    // Initialise
    delay(500);
    Serial.println("\n--- Initializing System ---");
    delay(100);

    initJoints(1, 1, 1); 


    engine.init();
    stepper1 = engine.stepperConnectToPin(J1_STEP_PIN);
    stepper1->setDirectionPin(J1_DIR_PIN, true);
    stepper1->setAutoEnable(true);
    stepper1->setSpeedInHz(000);      
    stepper1->setAcceleration(20000);     


    stepper2 = engine.stepperConnectToPin(J2_STEP_PIN);
    stepper2->setDirectionPin(J2_DIR_PIN, true);
    stepper2->setAutoEnable(true);
    stepper2->setSpeedInHz(000);      
    stepper2->setAcceleration(20000); 
    // stepper2->runBackward();
    Serial.println("t, j1_dot, j2_dot");
    setupRuckig();
    
}


String inputString = "";

float j1_angle = 0;
float j2_angle = 0;

// Joint limits
const float J1_MIN = -180;
const float J1_MAX = 360;

const float J2_MIN = -180;
const float J2_MAX = 360;

float t = 0;
Result res;

void loop() {

  while (Serial.available()) {
    char c = Serial.read();

    if (c == '\n') {
      int commaIndex = inputString.indexOf(',');

      if (commaIndex > 0) {
        String j1_str = inputString.substring(0, commaIndex);
        String j2_str = inputString.substring(commaIndex + 1);

        j1_angle = j1_str.toFloat();
        j2_angle = j2_str.toFloat();

        // Apply limits
        j1_angle = constrain(j1_angle, J1_MIN, J1_MAX);
        // j2_angle = constrain(j2_angle, J2_MIN, J2_MAX);

        // Serial.print("J1: ");
        // Serial.print(j1_angle);

        // Serial.print("  J2: ");
        // Serial.println(j2_angle);

        input.target_position = {j1_angle/360, j2_angle/360};
      }

      inputString = "";
    }
    else {
      inputString += c;
    }
  }


    res = ruck.update(input, output);

    if (res == Result::Working) {
        t += 0.01;
        
        // 2. CONVERT REVOLUTIONS BACK TO DEGREES FOR THE MOTORS
        // Multiply Ruckig's output by 360.0 to get Deg/sec, then by Steps/Deg
        float j1_velocity = (output.new_velocity[0] * 360.0) * J1_STEPS_PER_DEG;
        float j2_velocity = (output.new_velocity[1] * 360.0) * J2_STEPS_PER_DEG;

        // --- JOINT 1 ---
        // CRITICAL: Must use abs() in deadband so negative speeds don't trigger a stop!
        if (abs(j1_velocity) < 0.1) {
            stepper1->stopMove();
        } else {
            stepper1->setSpeedInHz(abs(j1_velocity));
            if (j1_velocity > 0) stepper1->runForward();
            else stepper1->runBackward();
        }

        // --- JOINT 2 ---
        if (abs(j2_velocity) < 0.1) {
            stepper2->stopMove();
        } else {
            stepper2->setSpeedInHz(abs(j2_velocity));
            if (j2_velocity > 0) stepper2->runForward();
            else stepper2->runBackward();
        }
        
        Serial.printf("%f,%f,%f\n", t, j1_velocity, j2_velocity);
        output.pass_to_input(input);
        
    } else if (res == Result::Finished) {
        static unsigned long lastPrint = 0;
        if (millis() - lastPrint > 1000) {
            Serial.println("Result::Finished - Target reached!");
            lastPrint = millis();
        }
        stepper1->stopMove();
        stepper2->stopMove();
    } else {
        Serial.printf("Ruckig Error Code: %d\n", (int)res);
        delay(1000); 
    }

    // 10ms cycle time
    delayMicroseconds(10000); 
}